-- =============================================
-- AMBRIA OPS — DUMMY / DEMO DATA (temporary, until real data is entered)
-- Run in Supabase SQL Editor. Safe to run multiple times:
--   * tasks use fixed ids with ON CONFLICT DO NOTHING
--   * chemical_usage only inserts if the table is empty (avoids duplicates)
-- =============================================

-- 1. TASKS (assigned to real employees, mixed statuses to show the full flow)
INSERT INTO tasks (id, property, department, category, title, title_hi, area, time_block, priority, assigned_to, assignee_name, status, task_date, started_at, started_by, completion_photo, completion_note, completion_requested_at, completed_at, completed_by, approved_by, approved_at, rejection_note)
VALUES
  ('t_seed_0_0', 'pp', 'h', 'daily', 'Water all plants and lawn', 'सभी पौधों और लॉन में पानी दें', 'Lawn & Garden', '6:00 - 8:00 AM', 'medium', 'pp_pawan', 'Pawan', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_1_1', 'pp', 'h', 'daily', 'Remove weeds from flower beds', 'फूलों की क्यारियों से खरपतवार हटाएं', 'Flower Beds', '8:00 - 9:00 AM', 'medium', 'pp_pawan', 'Pawan', 'completion_requested', CURRENT_DATE, NOW(), 'pp_pawan', '["https://picsum.photos/seed/t_seed_1_1/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_2_2', 'pp', 'h', 'weekly', 'Trim hedges and bushes', 'झाड़ियों की कटाई करें', 'Boundary', 'Monday', 'medium', 'pp_pawan', 'Pawan', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_3_3', 'pp', 'h', 'monthly', 'Apply fertilizer to lawn', 'लॉन में खाद डालें', 'Main Lawn', '1st of month', 'medium', 'pp_pawan', 'Pawan', 'completion_requested', CURRENT_DATE, NOW(), 'pp_pawan', '["https://picsum.photos/seed/t_seed_3_3/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_4_0', 'pp', 'h', 'daily', 'Water all plants and lawn', 'सभी पौधों और लॉन में पानी दें', 'Lawn & Garden', '6:00 - 8:00 AM', 'medium', 'pp_dayashankar', 'Dayashankar', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_5_1', 'pp', 'h', 'daily', 'Remove weeds from flower beds', 'फूलों की क्यारियों से खरपतवार हटाएं', 'Flower Beds', '8:00 - 9:00 AM', 'medium', 'pp_dayashankar', 'Dayashankar', 'completion_requested', CURRENT_DATE, NOW(), 'pp_dayashankar', '["https://picsum.photos/seed/t_seed_5_1/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_6_2', 'pp', 'h', 'weekly', 'Trim hedges and bushes', 'झाड़ियों की कटाई करें', 'Boundary', 'Monday', 'medium', 'pp_dayashankar', 'Dayashankar', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_7_3', 'pp', 'h', 'monthly', 'Apply fertilizer to lawn', 'लॉन में खाद डालें', 'Main Lawn', '1st of month', 'medium', 'pp_dayashankar', 'Dayashankar', 'completion_requested', CURRENT_DATE, NOW(), 'pp_dayashankar', '["https://picsum.photos/seed/t_seed_7_3/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_8_0', 'pp', 'k', 'daily', 'Clean all washrooms', 'सभी वॉशरूम साफ करें', 'Washrooms', '7:00 - 9:00 AM', 'medium', 'pp_poonam', 'Poonam', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_9_1', 'pp', 'k', 'daily', 'Mop banquet hall floor', 'बैंक्वेट हॉल का फर्श पोंछें', 'Banquet Hall', '9:00 - 10:00 AM', 'medium', 'pp_poonam', 'Poonam', 'completion_requested', CURRENT_DATE, NOW(), 'pp_poonam', '["https://picsum.photos/seed/t_seed_9_1/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_10_2', 'pp', 'k', 'daily', 'Polish glass doors and windows', 'शीशे के दरवाजे साफ करें', 'Entrance', '10:00 - 11:00 AM', 'medium', 'pp_poonam', 'Poonam', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_11_3', 'pp', 'k', 'weekly', 'Deep clean carpets', 'कालीन की गहरी सफाई', 'Halls', 'Tuesday', 'medium', 'pp_poonam', 'Poonam', 'completion_requested', CURRENT_DATE, NOW(), 'pp_poonam', '["https://picsum.photos/seed/t_seed_11_3/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_12_4', 'pp', 'k', 'monthly', 'Sanitize kitchen area', 'रसोई क्षेत्र सैनिटाइज करें', 'Kitchen', '1st of month', 'medium', 'pp_poonam', 'Poonam', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_13_0', 'pp', 'k', 'daily', 'Clean all washrooms', 'सभी वॉशरूम साफ करें', 'Washrooms', '7:00 - 9:00 AM', 'medium', 'pp_neeru', 'Neeru', 'in_progress', CURRENT_DATE, NOW(), 'pp_neeru', '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_14_1', 'pp', 'k', 'daily', 'Mop banquet hall floor', 'बैंक्वेट हॉल का फर्श पोंछें', 'Banquet Hall', '9:00 - 10:00 AM', 'medium', 'pp_neeru', 'Neeru', 'completed', CURRENT_DATE, NULL, NULL, '["https://picsum.photos/seed/t_seed_14_1/500/400"]', NULL, NULL, NOW(), 'abhishek', 'abhishek', NOW(), NULL),
  ('t_seed_15_2', 'pp', 'k', 'daily', 'Polish glass doors and windows', 'शीशे के दरवाजे साफ करें', 'Entrance', '10:00 - 11:00 AM', 'medium', 'pp_neeru', 'Neeru', 'in_progress', CURRENT_DATE, NOW(), 'pp_neeru', '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_16_3', 'pp', 'k', 'weekly', 'Deep clean carpets', 'कालीन की गहरी सफाई', 'Halls', 'Tuesday', 'medium', 'pp_neeru', 'Neeru', 'completed', CURRENT_DATE, NULL, NULL, '["https://picsum.photos/seed/t_seed_16_3/500/400"]', NULL, NULL, NOW(), 'abhishek', 'abhishek', NOW(), NULL),
  ('t_seed_17_4', 'pp', 'k', 'monthly', 'Sanitize kitchen area', 'रसोई क्षेत्र सैनिटाइज करें', 'Kitchen', '1st of month', 'medium', 'pp_neeru', 'Neeru', 'in_progress', CURRENT_DATE, NOW(), 'pp_neeru', '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_18_0', 'ex', 'h', 'daily', 'Water all plants and lawn', 'सभी पौधों और लॉन में पानी दें', 'Lawn & Garden', '6:00 - 8:00 AM', 'medium', 'ex_sonu2', 'Sonu 2', 'completion_requested', CURRENT_DATE, NOW(), 'ex_sonu2', '["https://picsum.photos/seed/t_seed_18_0/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_19_1', 'ex', 'h', 'daily', 'Remove weeds from flower beds', 'फूलों की क्यारियों से खरपतवार हटाएं', 'Flower Beds', '8:00 - 9:00 AM', 'medium', 'ex_sonu2', 'Sonu 2', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_20_2', 'ex', 'h', 'weekly', 'Trim hedges and bushes', 'झाड़ियों की कटाई करें', 'Boundary', 'Monday', 'medium', 'ex_sonu2', 'Sonu 2', 'completion_requested', CURRENT_DATE, NOW(), 'ex_sonu2', '["https://picsum.photos/seed/t_seed_20_2/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_21_3', 'ex', 'h', 'monthly', 'Apply fertilizer to lawn', 'लॉन में खाद डालें', 'Main Lawn', '1st of month', 'medium', 'ex_sonu2', 'Sonu 2', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_22_0', 'ex', 'k', 'daily', 'Clean all washrooms', 'सभी वॉशरूम साफ करें', 'Washrooms', '7:00 - 9:00 AM', 'medium', 'ex_sunita', 'Sunita', 'completion_requested', CURRENT_DATE, NOW(), 'ex_sunita', '["https://picsum.photos/seed/t_seed_22_0/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_23_1', 'ex', 'k', 'daily', 'Mop banquet hall floor', 'बैंक्वेट हॉल का फर्श पोंछें', 'Banquet Hall', '9:00 - 10:00 AM', 'medium', 'ex_sunita', 'Sunita', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_24_2', 'ex', 'k', 'daily', 'Polish glass doors and windows', 'शीशे के दरवाजे साफ करें', 'Entrance', '10:00 - 11:00 AM', 'medium', 'ex_sunita', 'Sunita', 'completion_requested', CURRENT_DATE, NOW(), 'ex_sunita', '["https://picsum.photos/seed/t_seed_24_2/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_25_3', 'ex', 'k', 'weekly', 'Deep clean carpets', 'कालीन की गहरी सफाई', 'Halls', 'Tuesday', 'medium', 'ex_sunita', 'Sunita', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_26_4', 'ex', 'k', 'monthly', 'Sanitize kitchen area', 'रसोई क्षेत्र सैनिटाइज करें', 'Kitchen', '1st of month', 'medium', 'ex_sunita', 'Sunita', 'completion_requested', CURRENT_DATE, NOW(), 'ex_sunita', '["https://picsum.photos/seed/t_seed_26_4/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_27_0', 'ex', 'k', 'daily', 'Clean all washrooms', 'सभी वॉशरूम साफ करें', 'Washrooms', '7:00 - 9:00 AM', 'medium', 'ex_ragini', 'Ragini', 'completed', CURRENT_DATE, NULL, NULL, '["https://picsum.photos/seed/t_seed_27_0/500/400"]', NULL, NULL, NOW(), 'abhishek', 'abhishek', NOW(), NULL),
  ('t_seed_28_1', 'ex', 'k', 'daily', 'Mop banquet hall floor', 'बैंक्वेट हॉल का फर्श पोंछें', 'Banquet Hall', '9:00 - 10:00 AM', 'medium', 'ex_ragini', 'Ragini', 'in_progress', CURRENT_DATE, NOW(), 'ex_ragini', '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_29_2', 'ex', 'k', 'daily', 'Polish glass doors and windows', 'शीशे के दरवाजे साफ करें', 'Entrance', '10:00 - 11:00 AM', 'medium', 'ex_ragini', 'Ragini', 'completed', CURRENT_DATE, NULL, NULL, '["https://picsum.photos/seed/t_seed_29_2/500/400"]', NULL, NULL, NOW(), 'abhishek', 'abhishek', NOW(), NULL),
  ('t_seed_30_3', 'ex', 'k', 'weekly', 'Deep clean carpets', 'कालीन की गहरी सफाई', 'Halls', 'Tuesday', 'medium', 'ex_ragini', 'Ragini', 'in_progress', CURRENT_DATE, NOW(), 'ex_ragini', '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_31_4', 'ex', 'k', 'monthly', 'Sanitize kitchen area', 'रसोई क्षेत्र सैनिटाइज करें', 'Kitchen', '1st of month', 'medium', 'ex_ragini', 'Ragini', 'completed', CURRENT_DATE, NULL, NULL, '["https://picsum.photos/seed/t_seed_31_4/500/400"]', NULL, NULL, NOW(), 'abhishek', 'abhishek', NOW(), NULL),
  ('t_seed_32_0', 'mk', 'h', 'daily', 'Water all plants and lawn', 'सभी पौधों और लॉन में पानी दें', 'Lawn & Garden', '6:00 - 8:00 AM', 'medium', 'mk_mukesh', 'Mukesh', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_33_1', 'mk', 'h', 'daily', 'Remove weeds from flower beds', 'फूलों की क्यारियों से खरपतवार हटाएं', 'Flower Beds', '8:00 - 9:00 AM', 'medium', 'mk_mukesh', 'Mukesh', 'completion_requested', CURRENT_DATE, NOW(), 'mk_mukesh', '["https://picsum.photos/seed/t_seed_33_1/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_34_2', 'mk', 'h', 'weekly', 'Trim hedges and bushes', 'झाड़ियों की कटाई करें', 'Boundary', 'Monday', 'medium', 'mk_mukesh', 'Mukesh', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_35_3', 'mk', 'h', 'monthly', 'Apply fertilizer to lawn', 'लॉन में खाद डालें', 'Main Lawn', '1st of month', 'medium', 'mk_mukesh', 'Mukesh', 'completion_requested', CURRENT_DATE, NOW(), 'mk_mukesh', '["https://picsum.photos/seed/t_seed_35_3/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_36_0', 'mk', 'k', 'daily', 'Clean all washrooms', 'सभी वॉशरूम साफ करें', 'Washrooms', '7:00 - 9:00 AM', 'medium', 'mk_sadna', 'Sadna', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_37_1', 'mk', 'k', 'daily', 'Mop banquet hall floor', 'बैंक्वेट हॉल का फर्श पोंछें', 'Banquet Hall', '9:00 - 10:00 AM', 'medium', 'mk_sadna', 'Sadna', 'completion_requested', CURRENT_DATE, NOW(), 'mk_sadna', '["https://picsum.photos/seed/t_seed_37_1/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_38_2', 'mk', 'k', 'daily', 'Polish glass doors and windows', 'शीशे के दरवाजे साफ करें', 'Entrance', '10:00 - 11:00 AM', 'medium', 'mk_sadna', 'Sadna', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_39_3', 'mk', 'k', 'weekly', 'Deep clean carpets', 'कालीन की गहरी सफाई', 'Halls', 'Tuesday', 'medium', 'mk_sadna', 'Sadna', 'completion_requested', CURRENT_DATE, NOW(), 'mk_sadna', '["https://picsum.photos/seed/t_seed_39_3/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_40_4', 'mk', 'k', 'monthly', 'Sanitize kitchen area', 'रसोई क्षेत्र सैनिटाइज करें', 'Kitchen', '1st of month', 'medium', 'mk_sadna', 'Sadna', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_41_0', 'rs', 'k', 'daily', 'Clean all washrooms', 'सभी वॉशरूम साफ करें', 'Washrooms', '7:00 - 9:00 AM', 'medium', 'rs_suresh', 'Suresh', 'in_progress', CURRENT_DATE, NOW(), 'rs_suresh', '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_42_1', 'rs', 'k', 'daily', 'Mop banquet hall floor', 'बैंक्वेट हॉल का फर्श पोंछें', 'Banquet Hall', '9:00 - 10:00 AM', 'medium', 'rs_suresh', 'Suresh', 'completed', CURRENT_DATE, NULL, NULL, '["https://picsum.photos/seed/t_seed_42_1/500/400"]', NULL, NULL, NOW(), 'abhishek', 'abhishek', NOW(), NULL),
  ('t_seed_43_2', 'rs', 'k', 'daily', 'Polish glass doors and windows', 'शीशे के दरवाजे साफ करें', 'Entrance', '10:00 - 11:00 AM', 'medium', 'rs_suresh', 'Suresh', 'in_progress', CURRENT_DATE, NOW(), 'rs_suresh', '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_44_3', 'rs', 'k', 'weekly', 'Deep clean carpets', 'कालीन की गहरी सफाई', 'Halls', 'Tuesday', 'medium', 'rs_suresh', 'Suresh', 'completed', CURRENT_DATE, NULL, NULL, '["https://picsum.photos/seed/t_seed_44_3/500/400"]', NULL, NULL, NOW(), 'abhishek', 'abhishek', NOW(), NULL),
  ('t_seed_45_4', 'rs', 'k', 'monthly', 'Sanitize kitchen area', 'रसोई क्षेत्र सैनिटाइज करें', 'Kitchen', '1st of month', 'medium', 'rs_suresh', 'Suresh', 'in_progress', CURRENT_DATE, NOW(), 'rs_suresh', '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_46_0', 'rs', 'h', 'daily', 'Water all plants and lawn', 'सभी पौधों और लॉन में पानी दें', 'Lawn & Garden', '6:00 - 8:00 AM', 'medium', 'rs_ramu', 'Ramu', 'completion_requested', CURRENT_DATE, NOW(), 'rs_ramu', '["https://picsum.photos/seed/t_seed_46_0/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_47_1', 'rs', 'h', 'daily', 'Remove weeds from flower beds', 'फूलों की क्यारियों से खरपतवार हटाएं', 'Flower Beds', '8:00 - 9:00 AM', 'medium', 'rs_ramu', 'Ramu', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_48_2', 'rs', 'h', 'weekly', 'Trim hedges and bushes', 'झाड़ियों की कटाई करें', 'Boundary', 'Monday', 'medium', 'rs_ramu', 'Ramu', 'completion_requested', CURRENT_DATE, NOW(), 'rs_ramu', '["https://picsum.photos/seed/t_seed_48_2/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_49_3', 'rs', 'h', 'monthly', 'Apply fertilizer to lawn', 'लॉन में खाद डालें', 'Main Lawn', '1st of month', 'medium', 'rs_ramu', 'Ramu', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_50_0', 'pp', 'h', 'daily', 'Water all plants and lawn', 'सभी पौधों और लॉन में पानी दें', 'Lawn & Garden', '6:00 - 8:00 AM', 'medium', 'pp_sunil', 'Sunil', 'completion_requested', CURRENT_DATE, NOW(), 'pp_sunil', '["https://picsum.photos/seed/t_seed_50_0/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_51_1', 'pp', 'h', 'daily', 'Remove weeds from flower beds', 'फूलों की क्यारियों से खरपतवार हटाएं', 'Flower Beds', '8:00 - 9:00 AM', 'medium', 'pp_sunil', 'Sunil', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('t_seed_52_2', 'pp', 'h', 'weekly', 'Trim hedges and bushes', 'झाड़ियों की कटाई करें', 'Boundary', 'Monday', 'medium', 'pp_sunil', 'Sunil', 'completion_requested', CURRENT_DATE, NOW(), 'pp_sunil', '["https://picsum.photos/seed/t_seed_52_2/500/400"]', 'Task completed, photo attached.', NOW(), NULL, NULL, NULL, NULL, NULL),
  ('t_seed_53_3', 'pp', 'h', 'monthly', 'Apply fertilizer to lawn', 'लॉन में खाद डालें', 'Main Lawn', '1st of month', 'medium', 'pp_sunil', 'Sunil', 'pending', CURRENT_DATE, NULL, NULL, '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- 2. CHEMICAL USAGE (only if table currently empty)
INSERT INTO chemical_usage (property, chemical_name, chemical_name_hi, category, brand, quantity, unit, location, department, usage_date, created_by)
SELECT * FROM (VALUES
  ('pp', 'Floor Cleaner', 'फ्लोर क्लीनर', 'Floor Care', 'Kleanfix', 15, 'L', 'Banquet Hall', 'k', CURRENT_DATE, 'abhishek'),
  ('pp', 'Glass Cleaner', 'ग्लास क्लीनर', 'Glass', 'Kleanfix', 5, 'L', 'Main Entrance', 'k', CURRENT_DATE, 'abhishek'),
  ('pp', 'Toilet Cleaner', 'टॉयलेट क्लीनर', 'Washroom', 'Kleanfix', 8, 'L', 'Washrooms', 'k', CURRENT_DATE, 'abhishek'),
  ('pp', 'Lawn Fertilizer', 'लॉन खाद', 'Lawn/Garden', 'IFFCO', 20, 'kg', 'Main Lawn', 'k', CURRENT_DATE, 'abhishek'),
  ('ex', 'Floor Cleaner', 'फ्लोर क्लीनर', 'Floor Care', 'Kleanfix', 22, 'L', 'Aura Hall', 'k', CURRENT_DATE, 'abhishek'),
  ('ex', 'Disinfectant', 'कीटाणुनाशक', 'Washroom', 'Kleanfix', 12, 'L', 'Washrooms', 'k', CURRENT_DATE, 'abhishek'),
  ('ex', 'Lawn Fertilizer', 'लॉन खाद', 'Lawn/Garden', 'IFFCO', 25, 'kg', 'Valencia Lawn', 'k', CURRENT_DATE, 'abhishek'),
  ('mk', 'Floor Cleaner', 'फ्लोर क्लीनर', 'Floor Care', 'Kleanfix', 18, 'L', 'Emerald Hall', 'k', CURRENT_DATE, 'abhishek'),
  ('mk', 'Glass Cleaner', 'ग्लास क्लीनर', 'Glass', 'Kleanfix', 6, 'L', 'Alstonia', 'k', CURRENT_DATE, 'abhishek'),
  ('rs', 'Floor Cleaner', 'फ्लोर क्लीनर', 'Floor Care', 'Kleanfix', 7, 'L', 'Glasshouse', 'k', CURRENT_DATE, 'abhishek'),
  ('rs', 'Toilet Cleaner', 'टॉयलेट क्लीनर', 'Washroom', 'Kleanfix', 4, 'L', 'Washrooms', 'k', CURRENT_DATE, 'abhishek')
) AS v(property, chemical_name, chemical_name_hi, category, brand, quantity, unit, location, department, usage_date, created_by)
WHERE NOT EXISTS (SELECT 1 FROM chemical_usage);

-- Done. tasks: 54 rows. chemical_usage: 11 rows (if empty).
