// ═══════════════════════════════════════════════
// Ambria Workforce — Shared Constants
// ═══════════════════════════════════════════════

export const C = {
  maroon:"#7B1E2F", maroonLight:"#9A2E42", maroonSoft:"#F9F0F2",
  accent:"#C4956A", white:"#FFF", bg:"#FAFAFA", text:"#2D2D2D",
  tl:"#7A7A7A", border:"#EDEDED",
  green:"#2E8B57", gBg:"#EBF5F0",
  blue:"#3B6FC0", bBg:"#EBF1FA",
  yellow:"#C68A1D", yBg:"#FDF6E8",
  red:"#C0392B", rBg:"#FBEAE8",
  purple:"#6B21A8", pBg:"#6B21A815",
};

export const F = { b:"'Outfit',sans-serif", d:"'Cormorant Garamond',serif" };

export const L_EN = {
  // Nav
  myTasks:"My Tasks", calendar:"Calendar", dashboard:"Dashboard",
  allTasks:"All Tasks", team:"Team", areas:"Areas", attendance:"Attendance",
  login:"Sign In", logout:"Logout", roster:"Duty Roster", leaves:"Leaves",
  training:"Training", members:"Members", directives:"Assigned Tasks",
  // Auth
  username:"Username", password:"Password", enterUser:"Enter username",
  enterPass:"Enter password", invalidLogin:"Invalid credentials",
  contactSuper:"Contact supervisor",
  // Attendance
  checkIn:"Check In", checkOut:"Check Out", checkedIn:"Checked In",
  notCheckedIn:"Not checked in",
  // Status
  done:"Done", pending:"Pending", issue:"Issue", inProgress:"In Progress",
  total:"Total", photos:"Photos", issues:"Issues",
  // Tasks
  sop:"SOP Instructions", uploadPhoto:"Open Camera & Take Photo",
  photoNeeded:"Photo required", retakePhoto:"Retake (blurry?)",
  comment:"Comment", send:"Send", reassign:"Reassign",
  addTask:"Add Task", save:"Save", cancel:"Cancel", del:"Delete",
  taskTitle:"Task title", selectPerson:"Assign to", duration:"Duration",
  desc:"Description", daily:"Daily", weekly:"Weekly", monthly:"Monthly",
  high:"High", medium:"Medium", low:"Low",
  // Notif
  notif:"Notifications", noNotif:"No notifications", clearAll:"Clear",
  // Roles
  superAdmin:"Super Admin", admin:"Admin", staff:"Staff",
  noTasks:"No tasks", head:"Head", depts:"Departments",
  // Lang
  hi:"हिंदी", en:"English",
  // Preview
  preview:"Preview Staff", previewOff:"Back to Admin",
  previewAs:"Previewing as", previewDesc:"Staff phone view",
  steps:"1. Open 📖 → 2. 📸 Photo → 3. ☐ Done",
  teamTask:"Team", today:"Today",
  // Dept filters
  adminWork:"Admin", secWork:"Security", allWork:"All Depts",
  // Assigned tasks
  newDirective:"New Task", sendTo:"Send to",
  writeTask:"Write task details...", reply:"Reply",
  approve:"OK", reject:"Not OK", reqApproval:"Send for Approval",
  approved:"Approved", rejected:"Not OK - See Remarks",
  awaitApproval:"Awaiting Approval", directive:"Task from",
  replyHere:"Type reply...", addPhoto:"Add Photo",
  noDirectives:"No tasks assigned yet", remarks:"Remarks",
  okApproval:"OK ✅", notOk:"Not OK ❌",
  writeRemarks:"Write remarks...", markComplete:"Mark Complete",
  completedWork:"Completed", dueDate:"Target Date",
  overdue:"Overdue", dueOn:"Due",
  completionNote:"Add completion note...",
  completionPhoto:"Take photo of completed work",
  // Members
  members:"Members", addMember:"Add Member", removeMember:"Remove",
  memberName:"Name", memberDept:"Department", memberProp:"Property",
  joiningDate:"Joining Date", pastMembers:"Past Members",
  activeMembers:"Active Members", deactivate:"Deactivate",
  leftOn:"Left on", daysWithUs:"Days with Us",
  // Dashboard
  absentToday:"Absent Today", onLeave:"On Leave",
  allPresent:"All Present ✓", staffPerformance:"Staff Performance",
  criticalActions:"Critical Actions", suggestions:"Suggestions & Insights",
  noCritical:"All clear — no issues", presentToday:"Present Today",
  deptProgress:"Department Progress",
  // Duty Roster
  dayShift:"Day Shift (9AM–6PM)", nightShift:"Night Shift (6PM–9AM)",
  assignShift:"Assign Shift", saveRoster:"Save", thirdParty:"Third Party",
  ambriaSec:"Ambria", noRoster:"No shifts assigned",
  shiftStart:"Shift Start", shiftEnd:"Shift End", editRoster:"Edit",
  guard:"Guard", addGuard:"Add Guard", shift:"Shift",
  // Leave Management
  leaveRequest:"Leave Request", applyLeave:"Apply for Leave",
  casualLeave:"Casual", sickLeave:"Sick", otherLeave:"Other",
  leaveReason:"Reason", fromDate:"From", toDate:"To",
  myLeaves:"My Leaves", pendingLeaves:"Pending Requests",
  noLeaves:"No leave requests",
  leaveApproved:"Approved ✓", leaveRejected:"Rejected ✗",
  leaveType:"Leave Type", dayCount:"Days",
  // Chemical Guide
  chemCalc:"Chemical Calculator", monthlyQty:"Monthly Quantity",
  selectPropertyCalc:"Select Property",
  litersPerMonth:"L/month", kgPerMonth:"kg/month",
  banquetSqft:"Banquet (sqft)", lawnSqft:"Lawn (sqft)",
  washroomCount:"Washrooms", chemFormula:"Formula",
  // Training
  markWatched:"Mark as Watched", watched:"Watched ✓",
  notWatched:"Not Watched", staffProgress:"Staff Progress",
  trainingComplete:"Complete", trainingPct:"Completion %",
  watchVideo:"Watch Video",
  valetPlan:"Valet Planning",
};

export const L_HI = {
  myTasks:"मेरे काम", calendar:"कैलेंडर", dashboard:"डैशबोर्ड",
  allTasks:"सभी काम", team:"टीम", areas:"एरिया", attendance:"हाज़िरी",
  login:"लॉगिन", logout:"लॉगआउट", roster:"ड्यूटी रोस्टर", leaves:"छुट्टी",
  training:"प्रशिक्षण", members:"सदस्य", directives:"दिए गए काम",
  username:"यूज़रनेम", password:"पासवर्ड", enterUser:"यूज़रनेम डालें",
  enterPass:"पासवर्ड डालें", invalidLogin:"गलत जानकारी",
  contactSuper:"सुपरवाइज़र से संपर्क",
  checkIn:"चेक इन", checkOut:"चेक आउट", checkedIn:"चेक इन हुआ",
  notCheckedIn:"चेक इन नहीं",
  done:"पूरा", pending:"बाकी", issue:"समस्या", inProgress:"चल रहा",
  total:"कुल", photos:"फ़ोटो", issues:"समस्याएं",
  sop:"काम के निर्देश", uploadPhoto:"कैमरा खोलें फ़ोटो लें",
  photoNeeded:"फ़ोटो ज़रूरी", retakePhoto:"दोबारा लें (धुंधली?)",
  comment:"टिप्पणी", send:"भेजें", reassign:"दूसरे को दें",
  addTask:"नया काम", save:"सेव", cancel:"रद्द", del:"हटाएं",
  taskTitle:"काम का नाम", selectPerson:"किसको दें", duration:"समय",
  desc:"विवरण", daily:"रोज़ाना", weekly:"हफ़्ते", monthly:"महीने",
  high:"ज़रूरी", medium:"सामान्य", low:"कम",
  notif:"सूचनाएं", noNotif:"कोई सूचना नहीं", clearAll:"हटाएं",
  superAdmin:"सुपर एडमिन", admin:"एडमिन", staff:"कर्मचारी",
  noTasks:"कोई काम नहीं", head:"प्रमुख", depts:"विभाग",
  hi:"हिंदी", en:"English",
  preview:"कर्मचारी दृश्य", previewOff:"एडमिन वापस",
  previewAs:"देख रहे हैं", previewDesc:"फ़ोन दृश्य",
  steps:"1. 📖 खोलें → 2. 📸 फ़ोटो → 3. ☐ पूरा",
  teamTask:"टीम", today:"आज",
  adminWork:"प्रशासन", secWork:"सुरक्षा", allWork:"सभी विभाग",
  newDirective:"नया काम दें", sendTo:"भेजें",
  writeTask:"काम का विवरण लिखें...", reply:"जवाब",
  approve:"ठीक है", reject:"ठीक नहीं", reqApproval:"मंज़ूरी भेजें",
  approved:"मंज़ूर", rejected:"ठीक नहीं - टिप्पणी देखें",
  awaitApproval:"मंज़ूरी की प्रतीक्षा", directive:"काम",
  replyHere:"जवाब लिखें...", addPhoto:"फ़ोटो जोड़ें",
  noDirectives:"कोई काम नहीं दिया", remarks:"टिप्पणी",
  okApproval:"ठीक है ✅", notOk:"ठीक नहीं ❌",
  writeRemarks:"टिप्पणी लिखें...", markComplete:"पूरा करें",
  completedWork:"पूरा हुआ", dueDate:"लक्ष्य तिथि",
  overdue:"देरी", dueOn:"तक",
  completionNote:"पूरा करने की टिप्पणी...",
  completionPhoto:"पूरे काम की फ़ोटो लें",
  members:"सदस्य", addMember:"सदस्य जोड़ें", removeMember:"हटाएं",
  memberName:"नाम", memberDept:"विभाग", memberProp:"प्रॉपर्टी",
  joiningDate:"जोइनिंग तिथि", pastMembers:"पूर्व सदस्य",
  activeMembers:"सक्रिय सदस्य", deactivate:"निष्क्रिय करें",
  leftOn:"छोड़ा", daysWithUs:"हमारे साथ दिन",
  absentToday:"आज अनुपस्थित", onLeave:"छुट्टी पर",
  allPresent:"सभी उपस्थित ✓", staffPerformance:"स्टाफ प्रदर्शन",
  criticalActions:"महत्वपूर्ण कार्य", suggestions:"सुझाव और अंतर्दृष्टि",
  noCritical:"सब ठीक — कोई समस्या नहीं", presentToday:"आज उपस्थित",
  deptProgress:"विभाग प्रगति",
  dayShift:"दिन शिफ्ट (9AM–6PM)", nightShift:"रात शिफ्ट (6PM–9AM)",
  assignShift:"शिफ्ट दें", saveRoster:"सेव", thirdParty:"तृतीय पक्ष",
  ambriaSec:"अंब्रिया", noRoster:"कोई शिफ्ट नहीं",
  shiftStart:"शिफ्ट शुरू", shiftEnd:"शिफ्ट खत्म", editRoster:"बदलें",
  guard:"गार्ड", addGuard:"गार्ड जोड़ें", shift:"शिफ्ट",
  leaveRequest:"छुट्टी आवेदन", applyLeave:"छुट्टी के लिए आवेदन",
  casualLeave:"आकस्मिक", sickLeave:"बीमारी", otherLeave:"अन्य",
  leaveReason:"कारण", fromDate:"से", toDate:"तक",
  myLeaves:"मेरी छुट्टियाँ", pendingLeaves:"लंबित आवेदन",
  noLeaves:"कोई छुट्टी नहीं",
  leaveApproved:"मंज़ूर ✓", leaveRejected:"नामंज़ूर ✗",
  leaveType:"छुट्टी प्रकार", dayCount:"दिन",
  chemCalc:"केमिकल कैलकुलेटर", monthlyQty:"मासिक मात्रा",
  selectPropertyCalc:"प्रॉपर्टी चुनें",
  litersPerMonth:"लीटर/माह", kgPerMonth:"किग्रा/माह",
  banquetSqft:"बैंक्वेट (sqft)", lawnSqft:"लॉन (sqft)",
  washroomCount:"शौचालय", chemFormula:"फ़ॉर्मूला",
  markWatched:"देखा हुआ मार्क करें", watched:"देखा ✓",
  notWatched:"नहीं देखा", staffProgress:"स्टाफ प्रगति",
  trainingComplete:"पूर्ण", trainingPct:"पूर्णता %",
  watchVideo:"वीडियो देखें",
  valetPlan:"वैलेट प्लानिंग",
};

export const LANGS = { en: L_EN, hi: L_HI };

export const USERS = [
  {id:"abhishek",username:"abhishek",password:"ambria@2026",name:"Abhishek",role:"sa",prop:"all"},
  {id:"vicky",username:"vicky",password:"vicky@123",name:"Vicky Arya",role:"a",prop:"all"},
  {id:"pp_sonu",username:"sonu",password:"sonu@123",name:"Sonu Mali",role:"a",prop:"pp"},
  {id:"ex_mahesh",username:"mahesh",password:"mahesh@123",name:"Mahesh",role:"a",prop:"ex"},
  {id:"mk_rahees",username:"rahees",password:"rahees@123",name:"Rahees",role:"a",prop:"mk"},
  {id:"pp_pawan",username:"pawan",password:"pawan@123",name:"Pawan",role:"e",prop:"pp",dept:"h"},
  {id:"pp_dayashankar",username:"dayashankar",password:"daya@123",name:"Dayashankar",role:"e",prop:"pp",dept:"h"},
  {id:"pp_sunil",username:"sunil",password:"sunil@123",name:"Sunil",role:"e",prop:"pp",dept:"h"},
  {id:"pp_poonam",username:"poonam",password:"poonam@123",name:"Poonam",role:"e",prop:"pp",dept:"k"},
  {id:"pp_neeru",username:"neeru",password:"neeru@123",name:"Neeru",role:"e",prop:"pp",dept:"k"},
  {id:"pp_umesh",username:"umesh",password:"umesh@123",name:"Umesh",role:"e",prop:"pp",dept:"k"},
  {id:"pp_dinesh",username:"dinesh",password:"dinesh@123",name:"Dinesh",role:"e",prop:"pp",dept:"k"},
  {id:"pp_lalita",username:"lalita",password:"lalita@123",name:"Lalita",role:"e",prop:"pp",dept:"k"},
  {id:"ex_sunita",username:"sunita",password:"sunita@123",name:"Sunita",role:"e",prop:"ex",dept:"k"},
  {id:"ex_brijesh",username:"brijesh",password:"brijesh@123",name:"Brijesh",role:"e",prop:"ex",dept:"k"},
  {id:"ex_ragini",username:"ragini",password:"ragini@123",name:"Ragini",role:"e",prop:"ex",dept:"k"},
  {id:"ex_rani",username:"rani",password:"rani@123",name:"Rani",role:"e",prop:"ex",dept:"k"},
  {id:"ex_sonu2",username:"sonu2",password:"sonu2@123",name:"Sonu 2",role:"e",prop:"ex",dept:"h"},
  {id:"ex_dhruv",username:"dhruv",password:"dhruv@123",name:"Dhruv",role:"e",prop:"ex",dept:"h"},
  {id:"ex_kamlesh",username:"kamlesh",password:"kamlesh@123",name:"Kamlesh",role:"e",prop:"ex",dept:"h"},
  {id:"mk_sadna",username:"sadna",password:"sadna@123",name:"Sadna",role:"e",prop:"mk",dept:"k"},
  {id:"mk_lovekush",username:"lovekush",password:"lovekush@123",name:"Lovekush",role:"e",prop:"mk",dept:"k"},
  {id:"mk_akash",username:"akash",password:"akash@123",name:"Akash",role:"e",prop:"mk",dept:"k"},
  {id:"mk_ajay",username:"ajay",password:"ajay@123",name:"Ajay",role:"e",prop:"mk",dept:"k"},
  {id:"mk_mukesh",username:"mukesh",password:"mukesh@123",name:"Mukesh",role:"e",prop:"mk",dept:"h"},
  {id:"mk_tulsi",username:"tulsi",password:"tulsi@123",name:"Tulsi",role:"e",prop:"mk",dept:"h"},
  {id:"mk_akash_h",username:"akash_h",password:"akash@123",name:"Akash(H)",role:"e",prop:"mk",dept:"h"},
  {id:"rs_suresh",username:"suresh",password:"suresh@123",name:"Suresh",role:"e",prop:"rs",dept:"k"},
  {id:"rs_roma",username:"roma",password:"roma@123",name:"Roma",role:"e",prop:"rs",dept:"k"},
  {id:"rs_anita",username:"anita",password:"anita@123",name:"Anita",role:"e",prop:"rs",dept:"k"},
  {id:"rs_arjun",username:"arjun",password:"arjun@123",name:"Arjun",role:"e",prop:"rs",dept:"k"},
  {id:"rs_vinay",username:"vinay",password:"vinay@123",name:"Vinay",role:"e",prop:"rs",dept:"k"},
  {id:"rs_ramu",username:"ramu",password:"ramu@123",name:"Ramu",role:"e",prop:"rs",dept:"h"},
  {id:"sandeep",username:"sandeep",password:"sandeep@123",name:"Sandeep",role:"a",prop:"all",dept:"s"},
  {id:"rs_santosh",username:"santosh",password:"santosh@123",name:"Santosh",role:"e",prop:"rs",dept:"s"},
  {id:"ex_bhupender",username:"bhupender",password:"bhupender@123",name:"Bhupender",role:"e",prop:"ex",dept:"s"},
  {id:"mk_ajay_s",username:"ajay_s",password:"ajay@123",name:"Ajay (Sec)",role:"e",prop:"mk",dept:"s"},
];

export const PROPS = {
  pp:{id:"pp",name:"Ambria Pushpanjali",sn:"Pushpanjali",icon:"🏛️",loc:"Dwarka",tag:"3 Acres · 1500 Guests",
    specs:{Land:"3 Acres",Banquet:"14K sqft",Lawn:"40K sqft",Parking:"125+"},
    areas:[{id:"bq",n:"Banquet Hall",s:"14,000 sqft",i:"🏛️"},{id:"lw",n:"Grand Lawn",s:"40,000 sqft",i:"🌿"},{id:"wk",n:"Walkway",s:"120 ft",i:"🛤️"},{id:"vl",n:"Villa",s:"4 rooms",i:"🏠"},{id:"of",n:"Offices",s:"5",i:"🏢"},{id:"vw",n:"Villa WC",s:"7",i:"🚿"},{id:"gw",n:"Guest WC",s:"M+F",i:"🚻"},{id:"pk",n:"Parking",s:"125+",i:"🅿️"},{id:"en",n:"Entrance",s:"",i:"🚪"},{id:"gd",n:"Gardens",s:"",i:"🌺"}],
    depts:{
      h:{n:"Horticulture",i:"🌱",c:C.green,bg:C.gBg,hd:"Sonu Mali",m:[{id:"pp_pawan",n:"Pawan"},{id:"pp_dayashankar",n:"Dayashankar"},{id:"pp_sunil",n:"Sunil"}]},
      k:{n:"Housekeeping",i:"🧹",c:C.blue,bg:C.bBg,hd:"Poonam",m:[{id:"pp_poonam",n:"Poonam"},{id:"pp_neeru",n:"Neeru"},{id:"pp_umesh",n:"Umesh"},{id:"pp_dinesh",n:"Dinesh"},{id:"pp_lalita",n:"Lalita"}]},
      a:{n:"Admin",i:"📋",c:C.maroon,bg:C.maroonSoft,hd:"Sonu Mali",m:[{id:"pp_sonu",n:"Sonu Mali"}]},
      s:{n:"Security",i:"🛡️",c:C.purple,bg:C.pBg,hd:"Sandeep",m:[{id:"sandeep",n:"Sandeep"}]}},
    sh:"Sonu Mali"},
  ex:{id:"ex",name:"Ambria Exotica",sn:"Exotica",icon:"🌴",loc:"Dwarka",tag:"4 Acres · Aura & Valencia",
    specs:{Land:"4 Acres","Aura":"8.5K+27K","Valencia":"12K+8K",Parking:"300-350"},
    areas:[{id:"ag",n:"Aura Glass",s:"8,500 sqft",i:"🏛️"},{id:"al",n:"Aura Lawn",s:"27,000 sqft",i:"🌿"},{id:"vg",n:"Valencia Glass",s:"12,000 sqft",i:"✨"},{id:"vl2",n:"Valencia Lawn",s:"8,000 sqft",i:"🌳"},{id:"vp",n:"Poolside",s:"2,000 sqft",i:"🏊"},{id:"wk",n:"Walkway",s:"20K sqft",i:"🛤️"},{id:"pk",n:"Parking",s:"300-350",i:"🅿️"},{id:"wc",n:"Restrooms",s:"",i:"🚻"},{id:"en",n:"Entrance",s:"",i:"🚪"},{id:"gd",n:"Gardens",s:"",i:"🌺"}],
    depts:{
      h:{n:"Horticulture",i:"🌱",c:C.green,bg:C.gBg,hd:"Mahesh",m:[{id:"ex_sonu2",n:"Sonu 2"},{id:"ex_dhruv",n:"Dhruv"},{id:"ex_kamlesh",n:"Kamlesh"}]},
      k:{n:"Housekeeping",i:"🧹",c:C.blue,bg:C.bBg,hd:"Mahesh",m:[{id:"ex_sunita",n:"Sunita"},{id:"ex_brijesh",n:"Brijesh"},{id:"ex_ragini",n:"Ragini"},{id:"ex_rani",n:"Rani"}]},
      a:{n:"Admin",i:"📋",c:C.maroon,bg:C.maroonSoft,hd:"Mahesh",m:[{id:"ex_mahesh",n:"Mahesh"}]},
      s:{n:"Security",i:"🛡️",c:C.purple,bg:C.pBg,hd:"Sandeep",m:[{id:"ex_bhupender",n:"Bhupender"}]}},
    sh:"Mahesh"},
  mk:{id:"mk",name:"Ambria Manaktala",sn:"Manaktala",icon:"✨",loc:"Kapashera",tag:"3 Acres · Two Venues",
    specs:{Land:"3 Acres",Emerald:"10K+27K",Alstonia:"16K",Parking:"250+"},
    areas:[{id:"eg",n:"Emerald Glass",s:"10,000 sqft",i:"🏛️"},{id:"el",n:"Emerald Lawn",s:"27,000 sqft",i:"🌿"},{id:"ao",n:"Alstonia Lawn",s:"16,000 sqft",i:"🌳"},{id:"hn",n:"Hanger",s:"8,000 sqft",i:"🏗️"},{id:"b1",n:"Banquet",s:"10,000 sqft",i:"🎪"},{id:"dr",n:"Driveway",s:"400 ft",i:"🛤️"},{id:"pk",n:"Parking",s:"250+",i:"🅿️"},{id:"wc",n:"Restrooms",s:"",i:"🚻"},{id:"en",n:"Entrance",s:"",i:"🚪"},{id:"gd",n:"Gardens",s:"",i:"🌺"}],
    depts:{
      h:{n:"Horticulture",i:"🌱",c:C.green,bg:C.gBg,hd:"Rahees",m:[{id:"mk_mukesh",n:"Mukesh"},{id:"mk_tulsi",n:"Tulsi"},{id:"mk_akash_h",n:"Akash"}]},
      k:{n:"Housekeeping",i:"🧹",c:C.blue,bg:C.bBg,hd:"Rahees",m:[{id:"mk_sadna",n:"Sadna"},{id:"mk_lovekush",n:"Lovekush"},{id:"mk_akash",n:"Akash"},{id:"mk_ajay",n:"Ajay"}]},
      a:{n:"Admin",i:"📋",c:C.maroon,bg:C.maroonSoft,hd:"Rahees",m:[{id:"mk_rahees",n:"Rahees"}]},
      s:{n:"Security",i:"🛡️",c:C.purple,bg:C.pBg,hd:"Sandeep",m:[{id:"mk_ajay_s",n:"Ajay (Sec)"}]}},
    sh:"Rahees"},
  rs:{id:"rs",name:"Ambria Restro",sn:"Restro",icon:"🍽️",loc:"Palam Vihar",tag:"0.75 Acre · Restro · Cafe",
    specs:{Land:"0.75 Acre",Glass:"8K sqft",Restro:"800 sqft",Parking:"100+"},
    areas:[{id:"gl",n:"Glasshouse",s:"8,000 sqft",i:"🏛️"},{id:"lw",n:"Lawn",s:"1,500 sqft",i:"🌿"},{id:"re",n:"Restro",s:"800 sqft",i:"🍽️"},{id:"ca",n:"Cafe",s:"417 sqft",i:"☕"},{id:"rt",n:"Rooftop",s:"417 sqft",i:"🌇"},{id:"pk",n:"Parking",s:"100+",i:"🅿️"},{id:"ki",n:"Kitchen",s:"",i:"👨‍🍳"},{id:"wc",n:"Washrooms",s:"",i:"🚻"},{id:"en",n:"Entrance",s:"",i:"🚪"},{id:"gd",n:"Gardens",s:"",i:"🌺"}],
    depts:{
      h:{n:"Horticulture",i:"🌱",c:C.green,bg:C.gBg,hd:"Vicky Arya",m:[{id:"rs_ramu",n:"Ramu"}]},
      k:{n:"Housekeeping",i:"🧹",c:C.blue,bg:C.bBg,hd:"Vicky Arya",m:[{id:"rs_suresh",n:"Suresh"},{id:"rs_roma",n:"Roma"},{id:"rs_anita",n:"Anita"},{id:"rs_arjun",n:"Arjun"},{id:"rs_vinay",n:"Vinay"}]},
      a:{n:"Admin",i:"📋",c:C.maroon,bg:C.maroonSoft,hd:"Vicky Arya",m:[{id:"vicky",n:"Vicky Arya"}]},
      s:{n:"Security",i:"🛡️",c:C.purple,bg:C.pBg,hd:"Sandeep",m:[{id:"rs_santosh",n:"Santosh"}]}},
    sh:"Vicky Arya"},
};
